/**
 * EXTENDED BEST-PRACTICE KNOWLEDGE BASE.
 *
 * The original seed covered 16 languages with the essentials. An enterprise portal that claims to
 * manage *any* software needs more breadth (Kotlin, Swift, Scala, Elixir, Terraform, Dart, Perl,
 * Lua, R, MATLAB, Haskell, Solidity, PowerShell, Groovy, Objective-C, VB.NET, Delphi) and more
 * depth in the ones that carry most production risk (a11y, API design, concurrency, supply chain,
 * observability, data privacy).
 *
 * Every rule is written to be CHECKABLE — it names the thing to look for, not a platitude. Rules
 * are merged with the base seed by `seedBestPractices()`; `INSERT OR IGNORE` keeps re-seeding safe.
 */
export const EXTENDED_PRACTICES = [
  /* ── cross-cutting: the rules that matter regardless of language ── */
  { language: 'general', category: 'security', title: 'Validate at the trust boundary', rule: 'Every value crossing a trust boundary (HTTP body, query, header, queue message, file) is validated against an explicit schema before use — never trusted because "the client sends it".', severity: 'critical', rationale: 'Injection, type-confusion and mass-assignment all begin with unvalidated input.' },
  { language: 'general', category: 'security', title: 'Authorise per resource, not per route', rule: 'After authentication, check that THIS user may act on THIS record. A route-level role check does not prevent horizontal privilege escalation.', severity: 'critical', rationale: 'IDOR is the most common real-world breach in CRUD applications.' },
  { language: 'general', category: 'reliability', title: 'Every remote call has a timeout', rule: 'No network call is made without an explicit timeout and a defined behaviour on failure. A default of "wait forever" turns one slow dependency into a full outage.', severity: 'high', rationale: 'Unbounded waits exhaust the connection pool and cascade.' },
  { language: 'general', category: 'reliability', title: 'Make retried operations idempotent', rule: 'Any operation that can be retried (payment capture, message handling, webhook) carries an idempotency key and is safe to execute twice.', severity: 'high', rationale: 'At-least-once delivery is the norm; without idempotency retries double-charge.' },
  { language: 'general', category: 'observability', title: 'Log decisions, not noise', rule: 'Log the inputs to a decision and its outcome, with a correlation id — never log secrets, tokens, full payloads or personal data.', severity: 'medium', rationale: 'Logs that leak credentials are a breach; logs without correlation are unusable in an incident.' },
  { language: 'general', category: 'maintainability', title: 'Errors carry cause and context', rule: 'When re-throwing, preserve the original error as `cause` and add what was being attempted. Never swallow an error into an empty catch.', severity: 'high', rationale: 'A lost stack trace turns a five-minute fix into a day of guessing.' },
  { language: 'general', category: 'privacy', title: 'Minimise and expire personal data', rule: 'Collect only the personal data a feature needs, define its retention, and support export and erasure. Store a hash where the raw value is not needed.', severity: 'high', rationale: 'GDPR/CCPA obligations are design constraints, not paperwork.' },
  { language: 'general', category: 'supply-chain', title: 'Pin and verify dependencies', rule: 'Commit the lockfile, review new transitive dependencies, and keep a licence inventory. Never install from an unpinned tag in a build.', severity: 'high', rationale: 'Most modern compromises arrive through a dependency, not the code.' },
  { language: 'general', category: 'accessibility', title: 'Keyboard and screen-reader parity', rule: 'Every interactive element is reachable and operable by keyboard, has an accessible name, and a visible focus state. Colour is never the only signal.', severity: 'high', rationale: 'WCAG 2.1 AA is a legal requirement in most markets and a usability win for everyone.' },
  { language: 'general', category: 'api', title: 'Version and evolve, never break', rule: 'Additive changes only within a version: new optional fields are fine, removing or retyping a field is a breaking change that needs a new version and a deprecation window.', severity: 'high', rationale: 'A silently broken contract fails at the consumer, far from the change.' },

  /* ── JavaScript / TypeScript ── */
  { language: 'javascript', category: 'security', title: 'Never build SQL or HTML by concatenation', rule: 'Use parameterised queries and a templating layer that escapes by default. Treat `innerHTML`, `eval`, `new Function` and `dangerouslySetInnerHTML` as security-reviewed exceptions.', severity: 'critical', rationale: 'String-built SQL and HTML are the direct path to SQLi and XSS.' },
  { language: 'javascript', category: 'reliability', title: 'No floating promises', rule: 'Every promise is awaited or explicitly handled with `.catch`. An unhandled rejection can terminate the process.', severity: 'high', rationale: 'Node exits on unhandled rejections by default from v15.' },
  { language: 'javascript', category: 'performance', title: 'Batch queries — no N+1', rule: 'Loading a list then querying per item is an N+1. Use a single `IN` query, a join, or a dataloader.', severity: 'high', rationale: 'N+1 is the most common cause of a slow endpoint.' },
  { language: 'typescript', category: 'maintainability', title: 'No `any` at a boundary', rule: 'Public function signatures, API responses and props are fully typed. Use `unknown` plus narrowing where the type is genuinely unknown.', severity: 'high', rationale: '`any` disables exactly the checks you adopted TypeScript for.' },
  { language: 'typescript', category: 'maintainability', title: 'Model impossible states away', rule: 'Prefer discriminated unions over optional-flag soup (`{status:"ok",data} | {status:"error",error}` rather than `{data?, error?, loading?}`).', severity: 'medium', rationale: 'It makes invalid combinations unrepresentable rather than merely unlikely.' },

  /* ── Python ── */
  { language: 'python', category: 'security', title: 'Never use bare pickle or eval on input', rule: 'Deserialise untrusted data with `json`/`msgpack`, never `pickle`, `yaml.load` (use `safe_load`) or `eval`.', severity: 'critical', rationale: 'Unpickling attacker data is remote code execution.' },
  { language: 'python', category: 'reliability', title: 'No mutable default arguments', rule: 'Use `None` as the default and create the list/dict inside the function.', severity: 'high', rationale: 'The default is created once and shared by every call — a classic source of leaking state.' },
  { language: 'python', category: 'maintainability', title: 'Type-hint public functions', rule: 'Annotate parameters and return types on anything importable, and run mypy/pyright in CI.', severity: 'medium', rationale: 'Type hints catch a whole class of integration errors before runtime.' },
  { language: 'python', category: 'performance', title: 'Do not block the event loop', rule: 'In async code, never call blocking I/O or CPU-heavy work directly — use `run_in_executor` or a worker.', severity: 'high', rationale: 'One blocking call stalls every concurrent request on the loop.' },

  /* ── Java / Kotlin / Scala / Groovy (JVM) ── */
  { language: 'java', category: 'reliability', title: 'Close resources with try-with-resources', rule: 'Any `AutoCloseable` (stream, connection, statement) is opened in a try-with-resources block.', severity: 'high', rationale: 'Leaked connections exhaust the pool and take the service down under load.' },
  { language: 'java', category: 'security', title: 'Never deserialise untrusted Java objects', rule: 'Do not use `ObjectInputStream` on external data; prefer JSON with a strict schema.', severity: 'critical', rationale: 'Java deserialisation gadgets are a well-known RCE path.' },
  { language: 'kotlin', category: 'reliability', title: 'Do not defeat null-safety', rule: 'Avoid `!!`; prefer `?.`, `?:`, `requireNotNull` with a message, or a sealed type that makes absence explicit.', severity: 'high', rationale: '`!!` reintroduces exactly the NPE Kotlin was adopted to remove.' },
  { language: 'kotlin', category: 'reliability', title: 'Structured concurrency only', rule: 'Launch coroutines in a scope tied to a lifecycle; never use `GlobalScope`. Cancellation must propagate.', severity: 'high', rationale: 'Orphaned coroutines leak work and outlive the request that started them.' },
  { language: 'scala', category: 'maintainability', title: 'Total functions over partial ones', rule: 'Return `Option`/`Either` instead of throwing or returning null; avoid `.get` and `.head` on possibly-empty values.', severity: 'high', rationale: 'Partial functions move failures from compile time to production.' },
  { language: 'groovy', category: 'security', title: 'No dynamic evaluation of input', rule: 'Never pass request data to `Eval`, `GroovyShell` or `Script.evaluate`.', severity: 'critical', rationale: 'Dynamic evaluation of untrusted text is remote code execution.' },

  /* ── Go / Rust / C / C++ ── */
  { language: 'go', category: 'reliability', title: 'Handle every returned error', rule: 'Never discard an error with `_`. Wrap with `fmt.Errorf("...: %w", err)` so the cause survives.', severity: 'high', rationale: 'Go has no exceptions — a dropped error is a silently wrong program.' },
  { language: 'go', category: 'reliability', title: 'Propagate context', rule: 'Pass `context.Context` as the first parameter through the call chain and honour cancellation in loops and I/O.', severity: 'high', rationale: 'Without context a cancelled request keeps consuming resources.' },
  { language: 'rust', category: 'reliability', title: 'No unwrap in production paths', rule: 'Use `?`, `expect` with a diagnostic message, or explicit matching. Reserve `unwrap` for tests and provable invariants.', severity: 'high', rationale: 'An unwrap on `None`/`Err` panics the thread.' },
  { language: 'rust', category: 'security', title: 'Justify every unsafe block', rule: 'Each `unsafe` block carries a comment stating the invariant that makes it sound, and is kept as small as possible.', severity: 'high', rationale: '`unsafe` opts out of the guarantees that make Rust worth using.' },
  { language: 'cpp', category: 'security', title: 'No unbounded copies', rule: 'Never use `strcpy`, `sprintf`, `gets`. Use bounded APIs or `std::string`/`std::span`.', severity: 'critical', rationale: 'Unbounded copies are the classic buffer-overflow primitive.' },
  { language: 'cpp', category: 'reliability', title: 'RAII owns every resource', rule: 'Wrap memory, files, locks and sockets in smart pointers or RAII types; no raw `new`/`delete` in application code.', severity: 'high', rationale: 'Manual lifetime management leaks on every early return and exception.' },
  { language: 'c', category: 'security', title: 'Check every allocation and length', rule: 'Test the result of `malloc`/`realloc`, and validate lengths before any copy or index.', severity: 'critical', rationale: 'Unchecked allocation and arithmetic are the root of overflow and UAF bugs.' },

  /* ── C# / VB.NET / Objective-C / Swift / Dart ── */
  { language: 'csharp', category: 'reliability', title: 'Async all the way — never .Result', rule: 'Do not call `.Result` or `.Wait()` on a Task; make the caller async. Use `ConfigureAwait(false)` in libraries.', severity: 'high', rationale: 'Blocking on a task deadlocks under a synchronisation context.' },
  { language: 'csharp', category: 'security', title: 'Parameterise every query', rule: 'Use parameters or an ORM; never concatenate user input into SQL, even "internal" queries.', severity: 'critical', rationale: 'Internal endpoints become external after one refactor.' },
  { language: 'vbnet', category: 'maintainability', title: 'Option Strict On', rule: 'Enable `Option Strict` and `Option Explicit`; no implicit late-bound conversions.', severity: 'medium', rationale: 'Late binding turns compile-time errors into runtime ones.' },
  { language: 'swift', category: 'reliability', title: 'Avoid force unwrap and force try', rule: 'Prefer `guard let`/`if let` and `try?`/`do-catch`. `!` is a crash waiting for the unhappy path.', severity: 'high', rationale: 'Force unwrapping is the leading cause of iOS crashes.' },
  { language: 'swift', category: 'performance', title: 'No blocking work on the main actor', rule: 'Keep networking and heavy computation off the main thread; update UI on the main actor only.', severity: 'high', rationale: 'Main-thread blocking is perceived directly as a frozen app.' },
  { language: 'objectivec', category: 'reliability', title: 'Weak self in escaping blocks', rule: 'Capture `__weak typeof(self) weakSelf` in blocks retained by the object to avoid retain cycles.', severity: 'high', rationale: 'Retain cycles leak view controllers and their whole object graph.' },
  { language: 'dart', category: 'performance', title: 'Const constructors and keys in lists', rule: 'Use `const` widgets where possible and stable `Key`s in dynamic lists.', severity: 'medium', rationale: 'It prevents needless rebuilds and state mix-ups between list items.' },

  /* ── Ruby / PHP / Perl / Lua / Elixir / Haskell ── */
  { language: 'ruby', category: 'security', title: 'Strong parameters always', rule: 'Never pass raw `params` to a model; permit an explicit allow-list of attributes.', severity: 'critical', rationale: 'Mass assignment lets a request set fields such as `admin`.' },
  { language: 'php', category: 'security', title: 'Prepared statements only', rule: 'Use PDO/mysqli prepared statements; never interpolate into SQL. Escape on output with the templating layer.', severity: 'critical', rationale: 'PHP + string SQL remains the most exploited combination on the web.' },
  { language: 'perl', category: 'security', title: 'Enable taint mode for input handling', rule: 'Run with `-T` where input reaches system calls, and untaint through an explicit pattern match.', severity: 'high', rationale: 'Taint mode is Perl\'s built-in guard against passing user data to the shell.' },
  { language: 'lua', category: 'security', title: 'Never `loadstring` untrusted text', rule: 'Do not compile or evaluate data that came from a user; use a data format instead.', severity: 'critical', rationale: 'Evaluating input is arbitrary code execution in-process.' },
  { language: 'elixir', category: 'reliability', title: 'Supervise every process', rule: 'Start long-lived processes under a supervisor with an appropriate restart strategy — no bare `spawn`.', severity: 'high', rationale: 'An unsupervised process dies silently, taking its work with it.' },
  { language: 'haskell', category: 'maintainability', title: 'Avoid partial functions', rule: 'Do not use `head`, `fromJust`, or incomplete pattern matches; return `Maybe`/`Either` instead.', severity: 'high', rationale: 'Partial functions defeat the type system\'s guarantees at runtime.' },

  /* ── SQL / data ── */
  { language: 'sql', category: 'performance', title: 'Index what you filter and join on', rule: 'Every column used in a WHERE, JOIN or ORDER BY on a large table has a supporting index; verify with an execution plan.', severity: 'high', rationale: 'A missing index turns a millisecond query into a table scan.' },
  { language: 'sql', category: 'reliability', title: 'Migrations are reversible and additive', rule: 'Add columns nullable-first, backfill, then enforce. Never drop or rename in the same release that stops using it.', severity: 'critical', rationale: 'A destructive migration cannot be rolled back with the deploy.' },
  { language: 'sql', category: 'security', title: 'Least-privilege database users', rule: 'The application user has DML only — no DDL, no superuser. Migrations run as a separate identity.', severity: 'high', rationale: 'It contains the blast radius of an injection to data, not schema.' },

  /* ── infrastructure as code / shell / config ── */
  { language: 'terraform', category: 'security', title: 'No secrets in state or variables', rule: 'Pass secrets through a secret manager, mark variables `sensitive`, and keep state in an encrypted remote backend with locking.', severity: 'critical', rationale: 'Terraform state stores values in clear text.' },
  { language: 'terraform', category: 'reliability', title: 'Plan is reviewed before apply', rule: 'Never `apply` without a reviewed plan; pin provider and module versions.', severity: 'high', rationale: 'An unreviewed plan can destroy and recreate stateful resources.' },
  { language: 'shell', category: 'security', title: 'Quote every expansion', rule: 'Always `"$var"`, and use `set -euo pipefail`. Never pass unquoted input to `eval` or a subshell.', severity: 'high', rationale: 'Word splitting on a path with a space becomes command injection with a crafted one.' },
  { language: 'powershell', category: 'security', title: 'No Invoke-Expression on input', rule: 'Never pass user or file data to `Invoke-Expression`; use parameterised cmdlets and validate with `ValidateSet`.', severity: 'critical', rationale: 'IEX on untrusted text is code execution.' },
  { language: 'yaml', category: 'reliability', title: 'Schema-validate configuration', rule: 'Validate config files against a schema at startup and fail fast with a clear message.', severity: 'medium', rationale: 'A typo in YAML should not be discovered by a 3am page.' },
  { language: 'dockerfile', category: 'security', title: 'Non-root, pinned, minimal', rule: 'Run as a non-root user, pin the base image by digest, use multi-stage builds, and never bake secrets into a layer.', severity: 'high', rationale: 'Layers are public artefacts; a secret in one is a leaked secret forever.' },

  /* ── enterprise / legacy ── */
  { language: 'abap', category: 'performance', title: 'No SELECT inside LOOP', rule: 'Read the set once with FOR ALL ENTRIES or a join, then work in memory.', severity: 'high', rationale: 'A database round-trip per loop iteration is the classic ABAP performance defect.' },
  { language: 'abap', category: 'security', title: 'Authority-check every entry point', rule: 'Every report and RFC performs AUTHORITY-CHECK before reading or changing business data.', severity: 'critical', rationale: 'Without it any user with the transaction sees everything.' },
  { language: 'apex', category: 'reliability', title: 'Bulkify — no DML or SOQL in loops', rule: 'Collect records and perform one DML/SOQL outside the loop; write triggers for 200-record batches.', severity: 'critical', rationale: 'Salesforce governor limits abort the transaction outright.' },
  { language: 'cobol', category: 'maintainability', title: 'No hard-coded literals in business rules', rule: 'Put rates, thresholds and codes in a copybook or a table, not inline in PROCEDURE DIVISION.', severity: 'medium', rationale: 'A rate change should not require recompiling twenty programs.' },
  { language: 'delphi', category: 'reliability', title: 'Free what you create', rule: 'Every constructor is matched by a `try..finally Free`; prefer interfaces or ownership for lifetime.', severity: 'high', rationale: 'Leaks accumulate over a long-running desktop session until it fails.' },
  { language: 'solidity', category: 'security', title: 'Checks-Effects-Interactions', rule: 'Validate, then update state, and only then make an external call. Use a reentrancy guard on anything moving value.', severity: 'critical', rationale: 'Reentrancy has drained more value than every other smart-contract bug combined.' },
  { language: 'r', category: 'maintainability', title: 'No side effects on the global environment', rule: 'Avoid `<<-` and `attach`; return values instead. Set a seed for any stochastic analysis.', severity: 'medium', rationale: 'Reproducibility is the whole point of an analysis script.' },
  { language: 'matlab', category: 'performance', title: 'Preallocate and vectorise', rule: 'Preallocate arrays before a loop and prefer vectorised operations to element-wise loops.', severity: 'medium', rationale: 'Growing an array inside a loop reallocates on every iteration.' },
];
