/**
 * DEPTH FOR THE STACKS THAT ACTUALLY RUN, AND THE CATEGORIES THAT WERE EMPTY.
 *
 * The first two seeds bought breadth: 127 rules across 36 languages. Measured, that breadth was
 * thin exactly where it is used — the project under management is JavaScript, React and Node, and
 * those had **9, 0 and 0** rules respectively, while `testing` had 2, `accessibility` 1, `api` 1,
 * `observability` 1 and `privacy` 1 across the entire knowledge base.
 *
 * **Every rule here is written to be checkable from ONE FILE.** That is not a stylistic preference:
 * the compliance manager feeds these to the model as a checklist alongside a single file's source,
 * so a rule needing cross-file or runtime knowledge ("services must be idempotent end to end")
 * cannot be judged and produces confident noise. A rule that names a construct — `dangerouslySetInnerHTML`,
 * a missing `key`, a bare `catch {}` — can be pointed at a line.
 *
 * Rules are merged by `seedBestPractices()`; `UNIQUE(language, title)` and `INSERT OR IGNORE` make
 * re-seeding idempotent, so this file can grow without migration.
 */
export const DEPTH_PRACTICES = [
  /* ───────────────────────── JavaScript / Node ───────────────────────── */
  { language: 'javascript', category: 'security', title: 'No secrets in source', rule: 'API keys, tokens, connection strings and JWT secrets come from the environment or a secret store. A literal credential in source — including a "development" fallback like `process.env.JWT_SECRET || "dev-secret"` — is a finding.', severity: 'critical', rationale: 'A fallback secret ships to production the first time the variable is unset.' },
  { language: 'javascript', category: 'security', title: 'Do not disable TLS verification', rule: '`rejectUnauthorized: false` and `NODE_TLS_REJECT_UNAUTHORIZED=0` are never acceptable outside a test fixture. Fix the certificate chain instead.', severity: 'critical', rationale: 'It silently converts every HTTPS call into an unauthenticated one.' },
  { language: 'javascript', category: 'security', title: 'Use crypto-grade randomness for anything secret', rule: 'Tokens, session ids, password-reset codes and nonces use `crypto.randomUUID()` or `crypto.randomBytes`. `Math.random()` is for jitter and shuffling, never for a value an attacker must not guess.', severity: 'critical', rationale: '`Math.random` is seeded predictably and is not a CSPRNG.' },
  { language: 'javascript', category: 'security', title: 'Compare secrets in constant time', rule: 'Compare tokens, HMAC signatures and password hashes with `crypto.timingSafeEqual`, not `===`.', severity: 'high', rationale: 'A short-circuiting compare leaks the secret one byte at a time.' },
  { language: 'javascript', category: 'security', title: 'Never interpolate into a shell', rule: 'Use `execFile`/`spawn` with an argument array. `exec` with a template string containing any external value is command injection.', severity: 'critical', rationale: 'Shell metacharacters in a filename are enough to run arbitrary code.' },
  { language: 'javascript', category: 'security', title: 'Resolve and confine user-supplied paths', rule: 'A path built from request input is resolved and checked to stay inside its base directory before any fs call.', severity: 'critical', rationale: '`../../etc/passwd` is the whole of path traversal.' },
  { language: 'javascript', category: 'security', title: 'Do not deserialise untrusted input into code', rule: 'No `eval`, `new Function`, `vm.runInThisContext` or YAML unsafe-load on data that came from outside.', severity: 'critical', rationale: 'Deserialisation gadgets turn data into execution.' },
  { language: 'javascript', category: 'reliability', title: 'No empty catch', rule: 'A `catch` that neither handles, logs nor rethrows hides the failure. If ignoring is genuinely correct, say why in a comment.', severity: 'high', rationale: 'Silent failure is the hardest class of bug to diagnose later.' },
  { language: 'javascript', category: 'reliability', title: 'Await inside try, not outside', rule: 'An `await` on a rejecting promise outside the `try` block is not caught by it. Put the await where the handler can see it.', severity: 'high', rationale: 'A common refactoring slip that removes error handling without touching the catch.' },
  { language: 'javascript', category: 'reliability', title: 'Do not await in a loop when the work is independent', rule: 'Sequential awaits over an array serialise independent I/O. Use `Promise.all` (or `allSettled` when partial failure is acceptable) with a bounded concurrency.', severity: 'medium', rationale: 'Turns an O(n)-latency endpoint into a single round trip.' },
  { language: 'javascript', category: 'reliability', title: 'Handle Promise.all partial failure deliberately', rule: '`Promise.all` rejects on the first failure and abandons the rest. Where each result matters independently, use `allSettled` and report per item.', severity: 'medium', rationale: 'One failed item silently discarding nine successes is rarely intended.' },
  { language: 'javascript', category: 'reliability', title: 'Guard optional chaining on calls', rule: '`obj?.method?.()` — the parentheses need the dot. `obj?.method?()` is a syntax error, and `obj.method?.()` still throws if `obj` is null.', severity: 'medium', rationale: 'A real, repeated source of files that do not parse.' },
  { language: 'javascript', category: 'reliability', title: 'Check for null and undefined, not falsiness', rule: 'Use `== null` or `?? ` when zero and empty string are legitimate values. `if (!count)` treats 0 as missing.', severity: 'medium', rationale: 'Falsy checks silently mishandle 0, "" and false.' },
  { language: 'javascript', category: 'reliability', title: 'Close what you open', rule: 'File handles, database connections, intervals, listeners and abort controllers are released on every path, including the error path — `finally`, not the happy line.', severity: 'high', rationale: 'Leaked handles surface as an exhausted pool hours later.' },
  { language: 'javascript', category: 'reliability', title: 'Do not mutate a shared default', rule: 'Default parameters and module-level objects used as defaults must not be mutated; a `= {}` default is fresh per call but a module constant is not.', severity: 'medium', rationale: 'One request mutating a shared default corrupts every later one.' },
  { language: 'javascript', category: 'performance', title: 'Do not read whole files into memory', rule: 'Stream large files and responses rather than `readFileSync` into a string. Bound anything that grows with input size.', severity: 'medium', rationale: 'A 500 MB upload should not be a heap allocation.' },
  { language: 'javascript', category: 'performance', title: 'No blocking work on the event loop', rule: 'Synchronous crypto, large JSON parses, and `*Sync` fs calls in a request path stall every other request. Move them off the loop or make them async.', severity: 'high', rationale: 'Node serves all requests on one thread; one blocking call stalls all of them.' },
  { language: 'javascript', category: 'maintainability', title: 'Name the magic number', rule: 'A bare numeric or string literal carrying meaning (a timeout, a limit, a status code, a role name) becomes a named constant at module scope.', severity: 'low', rationale: 'The second occurrence is where they drift apart.' },
  { language: 'javascript', category: 'maintainability', title: 'Return early instead of nesting', rule: 'Guard clauses for the invalid cases first, then the main path unindented. Avoid more than three levels of nesting in one function.', severity: 'low', rationale: 'Depth, not length, is what makes a function unreadable.' },
  { language: 'javascript', category: 'observability', title: 'Errors reach the log with their stack', rule: 'Log the error object, not `err.message` alone, and attach what was being attempted. `catch (e) { log(e.message) }` throws away the stack.', severity: 'medium', rationale: 'A message without a stack cannot be located in the code.' },

  /* ───────────────────────────── React / JSX ──────────────────────────── */
  { language: 'react', category: 'security', title: 'dangerouslySetInnerHTML needs a sanitiser', rule: 'Any use must sanitise with a maintained library first, and the source of the HTML must be named in a comment. Never pass user content through it raw.', severity: 'critical', rationale: 'It is the one place React stops protecting you from XSS.' },
  { language: 'react', category: 'reliability', title: 'Effects clean up after themselves', rule: 'An effect that subscribes, sets an interval, adds a listener or starts a fetch returns a cleanup function. An async effect must ignore its result after unmount.', severity: 'high', rationale: 'Setting state on an unmounted component leaks and warns; uncleaned intervals leak forever.' },
  { language: 'react', category: 'reliability', title: 'The dependency array is complete', rule: 'Every value from the component scope used inside `useEffect`/`useMemo`/`useCallback` appears in its dependency array. An empty array on an effect that reads props is a stale-closure bug.', severity: 'high', rationale: 'Stale closures read yesterday\'s props and are invisible in review.' },
  { language: 'react', category: 'reliability', title: 'Keys are stable identities, not indices', rule: 'A list `key` is the item\'s own id. The array index reorders with the data and makes React reuse the wrong DOM node and state.', severity: 'high', rationale: 'Index keys corrupt input state the moment a list is sorted or filtered.' },
  { language: 'react', category: 'reliability', title: 'Do not call hooks conditionally', rule: 'Hooks run in the same order on every render — never inside an `if`, a loop, or after an early return.', severity: 'critical', rationale: 'Conditional hooks desynchronise React\'s internal state list.' },
  { language: 'react', category: 'reliability', title: 'Update state from the previous value', rule: 'When the next state depends on the current one, use the functional form `setX(prev => …)`. Reading `x` directly in a handler captures the value at render time.', severity: 'medium', rationale: 'Batched updates make the direct form lose intermediate values.' },
  { language: 'react', category: 'performance', title: 'Do not create new objects in JSX props', rule: 'Inline object, array and arrow literals in props create a new identity on every render and defeat memoisation of the child.', severity: 'medium', rationale: 'It silently turns a memoised subtree back into a re-rendering one.' },
  { language: 'react', category: 'performance', title: 'Virtualise long lists', rule: 'A list that can exceed a few hundred rows is windowed, not rendered whole.', severity: 'medium', rationale: 'Thousands of DOM nodes make scrolling and memory both unacceptable.' },
  { language: 'react', category: 'accessibility', title: 'Interactive means button or link', rule: 'A `div` or `span` with `onClick` is invisible to keyboard and screen-reader users. Use `<button>` or `<a>`, or supply `role`, `tabIndex` and a key handler.', severity: 'high', rationale: 'This is the single most common accessibility defect in React code.' },
  { language: 'react', category: 'accessibility', title: 'Every control has an accessible name', rule: 'An icon-only button carries `aria-label`; an input is tied to a `<label htmlFor>`. Placeholder text is not a label.', severity: 'high', rationale: 'A screen reader announces an unnamed button as "button".' },
  { language: 'react', category: 'accessibility', title: 'Images carry meaningful alt text', rule: 'Informative images describe their content; decorative ones use `alt=""` so they are skipped. A filename is not alt text.', severity: 'medium', rationale: 'Missing alt makes content unreachable; wrong alt makes it noise.' },
  { language: 'react', category: 'accessibility', title: 'Do not remove the focus indicator', rule: '`outline: none` without an equally visible replacement leaves keyboard users unable to see where they are.', severity: 'high', rationale: 'Focus visibility is a WCAG 2.1 AA requirement.' },
  { language: 'react', category: 'accessibility', title: 'Modals trap focus and are escapable', rule: 'A dialog moves focus in, keeps Tab inside it, closes on Escape, and returns focus to the trigger. It carries `role="dialog"` and `aria-modal`.', severity: 'high', rationale: 'Focus escaping behind a modal strands keyboard users.' },
  { language: 'react', category: 'maintainability', title: 'Loading, empty and error are all rendered', rule: 'A component that fetches renders all four states. A bare spinner with no error branch shows an infinite spinner when the request fails.', severity: 'medium', rationale: 'The failure path is the one users hit on a bad network.' },
  { language: 'react', category: 'maintainability', title: 'Do not render objects as children', rule: 'Rendering an object or an unknown value directly throws or prints `[object Object]`. Format explicitly, and guard values that come from an API.', severity: 'medium', rationale: 'A shape change upstream becomes a blank screen.' },

  /* ───────────────────────────── TypeScript ───────────────────────────── */
  { language: 'typescript', category: 'reliability', title: 'No non-null assertion on external data', rule: '`!` asserts a fact the compiler cannot check. On API responses and DOM lookups, narrow with a check instead.', severity: 'high', rationale: 'It converts a compile-time guarantee into a runtime crash.' },
  { language: 'typescript', category: 'reliability', title: 'Do not cast to silence the compiler', rule: '`as X` on a value the compiler disagrees about is an assertion, not a conversion. Validate and narrow, or fix the type.', severity: 'high', rationale: 'The cast is exactly where the runtime shape and the declared one diverge.' },
  { language: 'typescript', category: 'maintainability', title: 'Discriminated unions over optional soup', rule: 'Model variants with a literal tag and required fields per variant rather than one type with many optionals.', severity: 'medium', rationale: 'Optionals let impossible combinations type-check.' },
  { language: 'typescript', category: 'maintainability', title: 'Exhaustive switches assert never', rule: 'A switch over a union ends in a `default` that assigns to `never`, so adding a variant is a compile error.', severity: 'medium', rationale: 'Without it a new case is silently unhandled.' },
  { language: 'typescript', category: 'security', title: 'Parse, do not assume, at the boundary', rule: 'An API response or request body is validated by a schema that returns a typed value. A type annotation on `await res.json()` is a lie the compiler believes.', severity: 'high', rationale: 'Types are erased at runtime; only a parse actually checks.' },

  /* ────────────────────────────── testing ─────────────────────────────── */
  { language: 'general', category: 'testing', title: 'Assert behaviour, not implementation', rule: 'A test asserts what the unit does — its return value, its effect — not which private helpers it called. Tests coupled to internals break on every refactor.', severity: 'medium', rationale: 'Implementation tests punish exactly the changes you want to encourage.' },
  { language: 'general', category: 'testing', title: 'Every test can fail', rule: 'A test with no assertion, or one asserting something always true (`expect(x).toBeDefined()` on a literal), reports success it never checked.', severity: 'high', rationale: 'A test that cannot fail is worse than none — it certifies.' },
  { language: 'general', category: 'testing', title: 'Cover the error path', rule: 'For every function with a failure mode, one test drives it: the rejected promise, the invalid input, the missing record.', severity: 'high', rationale: 'The happy path rarely breaks in production; the error path does.' },
  { language: 'general', category: 'testing', title: 'No sleep-based synchronisation', rule: 'Wait on the condition, not on the clock. A fixed `sleep` is flaky on a slow machine and slow on a fast one.', severity: 'medium', rationale: 'Timing-based waits are the main source of flaky suites.' },
  { language: 'general', category: 'testing', title: 'Tests are independent and order-free', rule: 'No test depends on another having run. Shared state is created and torn down per test.', severity: 'high', rationale: 'Order dependence turns one failure into a cascade with no obvious cause.' },
  { language: 'general', category: 'testing', title: 'Do not mock what you are testing', rule: 'Mock the boundary — the network, the clock, the filesystem — not the unit under test. A test whose subject is mocked verifies the mock.', severity: 'high', rationale: 'Over-mocking produces suites that pass while the product is broken.' },
  { language: 'general', category: 'testing', title: 'Name the scenario, not the function', rule: 'A test name states the condition and the expected outcome, so a failure report is readable without opening the file.', severity: 'low', rationale: '"test user" tells nobody what regressed.' },
  { language: 'general', category: 'testing', title: 'Fix the clock for time-dependent logic', rule: 'Anything reading the current time is tested against a fixed clock, including boundaries: midnight, month end, DST, leap day.', severity: 'medium', rationale: 'Date bugs appear once a year, in production.' },
  { language: 'javascript', category: 'testing', title: 'Await the assertion', rule: 'An assertion inside an un-awaited async callback runs after the test finished and its failure is lost. Await the promise or return it.', severity: 'high', rationale: 'The test passes while the assertion fails.' },

  /* ────────────────────────── API design & HTTP ───────────────────────── */
  { language: 'general', category: 'api', title: 'Status codes mean what they say', rule: '400 for a malformed request, 401 unauthenticated, 403 unauthorised, 404 absent, 409 conflict, 422 semantically invalid, 5xx only for a server fault. Never 200 with an error body.', severity: 'medium', rationale: 'Clients, proxies and monitoring all key off the status.' },
  { language: 'general', category: 'api', title: 'Errors are structured and safe', rule: 'An error response carries a stable machine-readable code and a human message — never a stack trace, SQL fragment or internal path.', severity: 'high', rationale: 'Stack traces in responses are reconnaissance for an attacker.' },
  { language: 'general', category: 'api', title: 'Every collection endpoint paginates', rule: 'A list endpoint has a bounded default page size and a documented maximum. "Return everything" fails the day the table grows.', severity: 'high', rationale: 'Unbounded responses are a self-inflicted denial of service.' },
  { language: 'general', category: 'api', title: 'Write endpoints accept an idempotency key', rule: 'POST operations with side effects accept a client-supplied key and return the original result on replay.', severity: 'high', rationale: 'The client cannot know whether a timed-out request took effect.' },
  { language: 'general', category: 'api', title: 'Rate-limit what can be abused', rule: 'Authentication, password reset, search and anything expensive carry a per-identity limit, and the limit is enforced server-side.', severity: 'high', rationale: 'Credential stuffing needs only an unlimited login endpoint.' },
  { language: 'general', category: 'api', title: 'Never accept the client\'s idea of who it is', rule: 'User id, role, price and totals come from the server\'s own state, not from the request body.', severity: 'critical', rationale: 'Mass assignment and price tampering both start here.' },

  /* ─────────────────────────── data & privacy ─────────────────────────── */
  { language: 'general', category: 'privacy', title: 'Personal data never reaches a log or a URL', rule: 'Email, phone, address, tokens and full request bodies are excluded from logs, and never placed in a query string where they land in proxy logs and history.', severity: 'high', rationale: 'Logs are replicated widely and retained long past their usefulness.' },
  { language: 'general', category: 'privacy', title: 'Hash what you do not need to read back', rule: 'Passwords use a memory-hard KDF (argon2, bcrypt, scrypt) with a per-record salt. Lookup identifiers that need not be reversible are hashed too.', severity: 'critical', rationale: 'SHA-256 alone is a hash, not a password scheme.' },
  { language: 'general', category: 'privacy', title: 'Deletion actually deletes', rule: 'An erasure request removes or irreversibly anonymises the data in backups, caches, search indexes and analytics — not just a `deleted` flag on the row.', severity: 'high', rationale: 'A soft delete is not erasure under GDPR.' },
  { language: 'sql', category: 'security', title: 'Least privilege for the application role', rule: 'The application connects with a role that cannot DROP, ALTER or read tables it does not use. Migrations run under a different, privileged role.', severity: 'high', rationale: 'It bounds the damage of an injection that gets through.' },
  { language: 'sql', category: 'performance', title: 'Every foreign key and filter column is indexed', rule: 'Columns used in JOIN, WHERE and ORDER BY have an index; composite indexes match the query\'s column order.', severity: 'high', rationale: 'A sequential scan on a growing table degrades without warning.' },
  { language: 'sql', category: 'reliability', title: 'Migrations are reversible and additive', rule: 'Add a column nullable, backfill, then enforce — never rename or drop in the same release that ships the code depending on it.', severity: 'high', rationale: 'A non-additive migration makes the deploy and the rollback both broken.' },
  { language: 'sql', category: 'reliability', title: 'Transactions cover the whole invariant', rule: 'Operations that must all succeed share one transaction, and it is kept short. A transaction spanning a network call holds locks for the duration.', severity: 'high', rationale: 'Partial writes leave data that no code path expects.' },

  /* ──────────────────────────── observability ─────────────────────────── */
  { language: 'general', category: 'observability', title: 'One correlation id spans the request', rule: 'A request id is generated at the edge, propagated to every service and job it triggers, and included in every log line.', severity: 'medium', rationale: 'Without it a distributed failure cannot be reassembled.' },
  { language: 'general', category: 'observability', title: 'Health checks test dependencies', rule: 'A readiness check verifies the database and critical downstreams, not just that the process is alive.', severity: 'medium', rationale: 'A process that answers 200 while its database is unreachable keeps taking traffic.' },
  { language: 'general', category: 'observability', title: 'Log levels mean something', rule: 'ERROR is something a human must act on. Warnings that fire constantly train everyone to ignore the log.', severity: 'low', rationale: 'An alert that is always on is not an alert.' },

  /* ──────────────────────── Python / Go / Java / C# ───────────────────── */
  { language: 'python', category: 'reliability', title: 'No mutable default argument', rule: 'A `[]` or `{}` default is created once at definition and shared across every call. Use `None` and build inside.', severity: 'high', rationale: 'State leaks between unrelated calls — a classic and silent bug.' },
  { language: 'python', category: 'reliability', title: 'Catch the specific exception', rule: 'A bare `except:` swallows `KeyboardInterrupt` and `SystemExit` too. Name the exception you expect.', severity: 'high', rationale: 'It makes the process unkillable and hides real errors.' },
  { language: 'python', category: 'reliability', title: 'Use a context manager for resources', rule: 'Files, sockets, locks and connections are acquired with `with`, so they close on the exception path too.', severity: 'medium', rationale: 'CPython\'s refcounting hides this until you run on another runtime.' },
  { language: 'python', category: 'security', title: 'No shell=True with external input', rule: 'Use `subprocess.run([...])` with a list. `shell=True` on an interpolated string is command injection.', severity: 'critical', rationale: 'The shell re-parses the string you carefully built.' },
  { language: 'go', category: 'reliability', title: 'Never discard an error', rule: 'Assigning an error to `_` discards a failure the compiler forced you to receive. Handle it or wrap it with `%w`.', severity: 'high', rationale: 'Go has no exceptions — a dropped error is a silently wrong result.' },
  { language: 'go', category: 'reliability', title: 'Context flows through every call', rule: 'Functions doing I/O take a `context.Context` as the first parameter and honour cancellation.', severity: 'high', rationale: 'Without it a cancelled request keeps its goroutines and connections alive.' },
  { language: 'go', category: 'reliability', title: 'defer the close beside the open', rule: 'Every `Open`, `Lock` and `Begin` is followed immediately by its `defer` counterpart, so a later return cannot skip it.', severity: 'medium', rationale: 'The leak appears when someone adds an early return months later.' },
  { language: 'java', category: 'reliability', title: 'Use try-with-resources', rule: 'Anything `AutoCloseable` is opened in a try-with-resources block rather than closed in a `finally` by hand.', severity: 'medium', rationale: 'A hand-written finally misses the exception-during-close case.' },
  { language: 'java', category: 'security', title: 'No Java deserialisation of untrusted bytes', rule: '`ObjectInputStream` on data from outside is remote code execution. Use JSON with an explicit schema.', severity: 'critical', rationale: 'Gadget chains exist in common libraries on every classpath.' },
  { language: 'csharp', category: 'reliability', title: 'ConfigureAwait(false) in libraries', rule: 'Library code awaits with `ConfigureAwait(false)` so it does not capture and depend on the caller\'s synchronisation context.', severity: 'medium', rationale: 'Capturing the context is how library calls deadlock a UI thread.' },
  { language: 'csharp', category: 'reliability', title: 'Never block on async', rule: '`.Result` and `.Wait()` on a task deadlock when a synchronisation context is captured. Await all the way up.', severity: 'high', rationale: 'The deadlock appears only under load or in a UI host.' },

  /* ──────────────────────────── CSS / markup ──────────────────────────── */
  { language: 'css', category: 'accessibility', title: 'Text meets the contrast ratio', rule: 'Body text holds at least 4.5:1 against its background, large text 3:1 — verified in both light and dark themes.', severity: 'high', rationale: 'Low contrast is the most reported accessibility failure, and dark mode is usually the one that fails.' },
  { language: 'css', category: 'accessibility', title: 'Respect prefers-reduced-motion', rule: 'Non-essential animation and parallax are disabled under `@media (prefers-reduced-motion: reduce)`.', severity: 'medium', rationale: 'Motion can cause nausea and migraine for a substantial minority.' },
  { language: 'css', category: 'accessibility', title: 'Do not suppress zoom or fix font sizes', rule: 'No `user-scalable=no`, and sizes in relative units so the browser\'s text setting is honoured.', severity: 'medium', rationale: 'Fixed pixel type makes the product unusable for low-vision users.' },
  { language: 'css', category: 'maintainability', title: 'Layers, not !important', rule: '`!important` is a symptom of a specificity fight. Fix the selector or use a cascade layer — and remember layers are resolved BEFORE specificity.', severity: 'low', rationale: 'Each !important makes the next override harder.' },
];
