/**
 * Chiavi i18n per il flusso "List an item", in tutte e quattro le lingue.
 *
 * NOTA SUL FORMATO, che è costato un giro a vuoto: `pick()` in I18nProvider fa
 * `path.split('.').reduce(...)`, cioè percorre un oggetto ANNIDATO. Una chiave scritta piatta come
 * `"lister.ai_generate": "..."` non viene mai trovata, `t()` cade sul fallback italiano e la UI
 * resta in italiano in ogni lingua — esattamente il sintomo osservato. Le chiavi vanno quindi
 * annidate sotto `lister: { ... }`.
 */
import fs from 'node:fs';
import path from 'node:path';

const REPO = process.argv[2] || process.cwd();
const PAGE = path.join(REPO, 'frontend/app/pages/BecomeLister.jsx');
const LOCALES = path.join(REPO, 'frontend/app/i18n/locales');

/** sottochiave → [it, en, fr, es] */
const T = {
  ai_lead_title:   ["Lascia che l'AI scriva l'annuncio per te", 'Let AI write your listing for you', "Laissez l'IA rédiger votre annonce", 'Deja que la IA escriba tu anuncio'],
  ai_lead_body:    ["Dalle foto caricate l'AI genererà un titolo accattivante, una descrizione completa e le condizioni d'uso. Potrai sempre modificare ogni dettaglio.", 'From your photos, AI will write a catchy title, a full description and the terms of use. You can edit every detail afterwards.', "À partir de vos photos, l'IA rédigera un titre accrocheur, une description complète et les conditions d'utilisation. Vous pourrez tout modifier ensuite.", 'A partir de tus fotos, la IA escribirá un título atractivo, una descripción completa y las condiciones de uso. Podrás editarlo todo después.'],
  ai_card_title:   ['Genera titolo, descrizione e condizioni', 'Generate title, description and terms', 'Générer titre, description et conditions', 'Genera título, descripción y condiciones'],
  ai_photos_pre:   ["L'AI analizzerà le", 'AI will analyse the', "L'IA analysera les", 'La IA analizará las'],
  ai_photos_post:  ['caricate per produrre un annuncio realistico.', 'you uploaded to produce a realistic listing.', 'que vous avez ajoutées pour produire une annonce réaliste.', 'que has subido para producir un anuncio realista.'],
  ai_photos_word:  ['foto', 'photos', 'photos', 'fotos'],
  ai_no_photos:    ['Torna allo step precedente e carica le foto per usare la generazione automatica.', 'Go back a step and upload photos to use automatic generation.', "Revenez à l'étape précédente et ajoutez des photos pour utiliser la génération automatique.", 'Vuelve al paso anterior y sube fotos para usar la generación automática.'],
  ai_analysing:    ['Sto analizzando le foto…', 'Analysing your photos…', 'Analyse des photos en cours…', 'Analizando las fotos…'],
  ai_generate:     ['Genera con AI', 'Generate with AI', "Générer avec l'IA", 'Generar con IA'],
  ai_regenerate:   ['Rigenera', 'Regenerate', 'Régénérer', 'Regenerar'],
  ai_done:         ["Annuncio generato dall'AI. Modifica liberamente.", 'Listing generated by AI. Edit it freely.', "Annonce générée par l'IA. Modifiez-la librement.", 'Anuncio generado por IA. Edítalo libremente.'],
  checking_photos: ['Controllo foto in corso…', 'Checking photos…', 'Vérification des photos…', 'Comprobando las fotos…'],
  field_title:     ['Titolo', 'Title', 'Titre', 'Título'],
  field_terms:     ["Condizioni d'uso", 'Terms of use', "Conditions d'utilisation", 'Condiciones de uso'],
  terms_help:      ['Aiuta i renter a sapere cosa aspettarsi.', 'Helps renters know what to expect.', "Aide les locataires à savoir à quoi s'attendre.", 'Ayuda a los inquilinos a saber qué esperar.'],
  catalog_hint:    ['Seleziona dal catalogo RentALL.', 'Pick from the RentALL catalogue.', 'Choisissez dans le catalogue RentALL.', 'Elige del catálogo RentALL.'],
  deposit_min:     ['Soglia minima accettabile (opzionale)', 'Minimum acceptable amount (optional)', 'Montant minimum acceptable (facultatif)', 'Importe mínimo aceptable (opcional)'],
  // passo 3 — prezzo
  price:           ['Prezzo', 'Price', 'Prix', 'Precio'],
  deposit:         ['Caparra', 'Deposit', 'Caution', 'Fianza'],
  deposit_numeric: ['Caparra (numerico)', 'Deposit (numeric)', 'Caution (numérique)', 'Fianza (numérica)'],
  range:           ['Range:', 'Range:', 'Fourchette :', 'Rango:'],
  unit_hour:       ['ora', 'hour', 'heure', 'hora'],
  unit_day:        ['giorno', 'day', 'jour', 'día'],
  unit_week:       ['settimana', 'week', 'semaine', 'semana'],
  // passo 4 — disponibilità
  step4_lead:      ['Quando e come potranno noleggiarlo. Poi pubblichi.', 'When and how people can rent it. Then you publish.', 'Quand et comment on peut le louer. Puis vous publiez.', 'Cuándo y cómo pueden alquilarlo. Luego publicas.'],
  // errori
  err_one_photo:   ['Carica almeno 1 foto per procedere', 'Upload at least 1 photo to continue', 'Ajoutez au moins 1 photo pour continuer', 'Sube al menos 1 foto para continuar'],
  err_title_short: ['Titolo troppo corto (min 3 caratteri)', 'Title too short (min 3 characters)', 'Titre trop court (3 caractères minimum)', 'Título demasiado corto (mín. 3 caracteres)'],
  err_desc_short:  ['Descrizione troppo corta (min 10 caratteri)', 'Description too short (min 10 characters)', 'Description trop courte (10 caractères minimum)', 'Descripción demasiado corta (mín. 10 caracteres)'],
  err_city:        ['Seleziona una città', 'Select a city', 'Sélectionnez une ville', 'Selecciona una ciudad'],
  err_photo_first: ['Carica almeno una foto prima di usare la generazione AI', 'Upload at least one photo before using AI generation', "Ajoutez au moins une photo avant d'utiliser la génération par IA", 'Sube al menos una foto antes de usar la generación con IA'],
  err_kyc:         ['Devi completare la verifica identità prima di pubblicare', 'You must complete identity verification before publishing', "Vous devez terminer la vérification d'identité avant de publier", 'Debes completar la verificación de identidad antes de publicar'],
};

const LANGS = ['it', 'en', 'fr', 'es'];

for (const [i, lang] of LANGS.entries()) {
  const file = path.join(LOCALES, `${lang}.json`);
  const json = JSON.parse(fs.readFileSync(file, 'utf8'));

  // Via le chiavi piatte del primo tentativo: irraggiungibili da `pick`, e lasciarle sarebbe
  // lasciare in giro una traduzione che sembra esserci e non viene mai letta.
  for (const k of Object.keys(json)) if (k.startsWith('lister.')) delete json[k];

  json.lister = json.lister || {};
  for (const [sub, values] of Object.entries(T)) json.lister[sub] = values[i];

  fs.writeFileSync(file, `${JSON.stringify(json, null, 2)}\n`, 'utf8');
}
console.log(`${Object.keys(T).length} chiavi × ${LANGS.length} lingue, annidate sotto "lister"`);

/* ---------------- sostituzioni residue nella pagina ---------------- */

let page = fs.readFileSync(PAGE, 'utf8');
const EXTRA = [
  ["L'AI analizzerà le", 'ai_photos_pre'],
  ['caricate per produrre un annuncio realistico.', 'ai_photos_post'],
  ['Quando e come potranno noleggiarlo. Poi pubblichi.', 'step4_lead'],
  ['Soglia minima accettabile (opzionale)', 'deposit_min'],
  ['Caparra (numerico)', 'deposit_numeric'],
];
let done = 0;
const missed = [];
for (const [needle, sub] of EXTRA) {
  const call = `{t('lister.${sub}', ${JSON.stringify(T[sub][0])})}`;
  if (page.includes(needle)) { page = page.replace(needle, call); done++; } else missed.push(needle.slice(0, 50));
}
fs.writeFileSync(PAGE, page, 'utf8');
console.log(`sostituzioni aggiuntive: ${done}/${EXTRA.length}`);
for (const m of missed) console.log(`   già sostituita o assente: ${m}`);
